# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tristan Germer – professional information
title_kurz: Tristan Germer
slogan: "When fate hands you lemons, make lemonade. – Dale Carnegie"
slogan_de: „Wenn das Schicksal uns eine Zitrone gibt – machen wir Zitronenlimonade daraus.“ — Dale Carnegie
hashtag: tristangermer
date: 2020-03-28
email: tgermer@me.com
phone: 0151 22651857
description: >- # this means to ignore newlines until "baseurl:"
  Professional information about Tristan Germer, M.Sc.
author: Tristan Germer
about: "Made in Germany, married to an other German. Likes IT, structuring, automation, hiking, skiing. Working at the Munich University of Applied Sciences (HM)."
editorial: Tristan Germer
publisher: |
  Tristan Germer<br>
  Petrarcastraße 32<br>
  80933 München
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
#url: "https://tgermer-123456.netlify.com"
url: "https://tristan-germer.de/dev"
url_imprint:
url_pravacy_statement:
webmaster_email: tgermer@hm.edu
webmaster_name: Tristan Germer
logo_nav: /assets/img/Studieninformationstag 2020 links.svg   #logoLinks.svg
twitter_username:
linkedin_username:
facebook_username:
youtube_username:
instagram_username:

twitter:
  username:
  card: summary


social:
  name: Hochschule&nbsp;München
  links:
    - https://twitter.com/HAW_Muenchen
    - https://www.facebook.com/HochschuleMuenchen
    - https://www.linkedin.com/school/hochschule-muenchen

lang: en_US

show_excerpts: true # set to true to show excerpts on the news(post) site

# paginate: 2
# paginate_path: "/blog/page:num/"

# Build settings
permalink: :title/
sass:
  sass_dir: css
plugins:
  - jekyll-seo-tag
  #- jekyll-paginate
  - jekyll-feed
  - jekyll-typogrify

# GLYNN – FTP Uploader
# gem install glynn --source http://gemcutter.org
# https://github.com/dmathieu/glynn
ftp_host: 'web713.can11.de'
ftp_dir: 'tristan-germer.de/dev'
ftp_passive: true
ftp_username: 'web713'
ftp_password: 'Otis#1910'
# run glynn

defaults:
  # jekyll-seo-tag START
  - scope:
      path: ""
    values:
      image: /assets/img/FB_01_1200x630.png # Allgemeines OpenGraph Bild
  # jekyll-seo-tag ENDE

# Eigene Einstellungen
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "page"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
